# Use the official Postgres image
FROM postgres:17-alpine

# Set environment variables
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose the Postgres default port
EXPOSE 5432